{
    "0": "Bucket \"It contains a bucket\"",
    "2": "Useless Sign \"Nobody dies to this\"",
    "4": "Impossible \"No reset on first non?!\"",
    "6": "Memeasma Sign \"Filled Memeasma\"",
    "8": "Four Shine \"Fever Time\"",
    "10": "Jelly Sign \"Green Jelly\"",
    "12": "00FF00 \"Green-Eyed Green Eyes\"",
    "14": "Gamer Hanasaka \"Jelly of the Mountain & Dew\"",
    "16": "Gamer Hanasaka \"Virgin Gap vs. Chad Restream\"",
    "18": "Cut-Open Box \"Small Box & Small Box\"",
    "20": "Cut-Open Box \"Large Box & Large Box\"",
    "22": "Malice Cannon \"Abusing Game Mechanics in the Dead of Night\"",
    "24": "Malice Cannon \"Day 7 of Abusing Game Mechanics in the Dead of Night\"",
    "26": "Anomalies \"Anomalies, Anomalies, Anomalies, & Anomalies\"",
    "30": "Challenge \"Hardest spell in Touhou\"",
    "32": "Shackles Sign \"Shackles a Criminal Takes Off Every Single Time\"",
    "34": "Fart of Strength \"Storm on Mt. Pooe\"",
    "36": "Fart of Strength \"Wind Blowing Down from Mt. Pooe\"",
    "38": "Jabroni \"Knock Out In Three Rounds\"",
    "40": "Jabroni \"Knock Out In Three Rounds\"",
    "42": "Cringe Collection \"Terribly Easy Spell\"",
    "44": "Cringe Collection \"Terrifyingly Easy Spell\"",
    "46": "Cringe Collection \"Double Black Death Butt\"",
    "50": "Cringe Collection \"Flying Insex Nest\"",
    "54": "Cringe Collection \"Border of Border & Border\"",
    "58": "Cringe Collection \"Mt. Togakushi Toss\"",
    "62": "Cringe Collection \"Night Parade of a Million Demons\"",
    "66": "Cringe Collection \"Deep Fog Labyrinth\"",
    "70": "Cringe Collection \"Wind God's Leaf-Veiling\"",
    "74": "Cringe Collection \"Tengu's Macroburst\"",
    "78": "Cringe Collection \"Torii Whorl-Wind\"",
    "82": "Cringe Collection \"Spring Kyoto Dolls\"",
    "86": "Cringe Collection \"Straw Doll Kamikaze\"",
    "90": "Cringe Collection \"Return Inanimateness\"",
    "94": "Cringe Collection \"Mercury Poison\"",
    "98": "Cringe Collection \"Princess Undine\"",
    "102": "Cringe Collection \"Philosopher's Stone\"",
    "106": "Cringe Collection \"Extending Arm\"",
    "110": "Cringe Collection \"Kappa's Pororoca\"",
    "114": "Cringe Collection \"Trauma in the Glimmering Depths\"",
    "118": "Cat's Walk \"When the cat is walking\"",
    "120": "Death \"Guaranteed miss\"",
    "122": "The Floating Dead \"Zombie Cirno\"",
    "124": "The Floating Dead \"Possessed Cirno\"",
    "126": "Rumia \"Eater of The Spleen\"",
    "128": "Rumia \"Eater of Everything Apart From The Spleen\"",
    "130": "Vampire Sign \"Needle Mountain (not the Remilia spell)\"",
    "132": "Redundance \"The Needles of Yore & the Needles of Yore\"",
    "134": "\"Rekindling of Dead Asses\"",
    "136": "\"Resurrection Butterfairy\"",
    "138": "Pain \"Eye Strain\"",
    "142": "Atomic Burger \"Nuclear Burger\"",
    "144": "Atomic Burger \"Burger Excursion\"",
    "145": "Atomic Burger \"Uncontainable Nuclear Burger\"",
    "146": "Chad Sign \"Petit Chad\"",
    "147": "Chad Sign \"Mega Chad\"",
    "148": "Chad Sign \"Giga Chad\"",
    "149": "Chad Sign \"Peta Chad\"",
    "150": "Blazing Burger \"Fixed Burger\"",
    "152": "Blazing Burger \"Burger Revolution\"",
    "153": "Blazing Burger \"Ten Evil Burgers\"",
    "154": "\"Cheese Meltdown\"",
    "156": "\"Hell's Tacomac\"",
    "158": "\"Hell's Artificial Burger\"",
    "160": "\"Subterranean Suction\"",
    "162": "Surfing \"This looks cool in scoring\"",
    "163": "Miracle \"Miracle Johnson\"",
    "164": "Safespot \"Sit on her hand\"",
    "165": "Graphic \"All Ancestors Sitting On Your Face\"",
    "166": "Tiny Taps \"Minimum Movement Simulator\"",
    "167": "Learn To Read \"It's Id, not ID\"",
    "168": "Reversion \"Seija flipped the previous spell\"",
    "169": "Go Big or Go Home \"No Vertical or bust\"",
    "170": "Don't pronounce it like \"Roar Shark\"",
    "171": "Discord \"The Members of TRC\"",
    "172": "Genetics \"Skill Issue\"",
    "173": "\"Philosophy of a Trolled Person\"",
    "174": "\"Subterranean Rose (but we are aboveground?!)\""
}