{
    "0": "Assassin's Bullet \"Speed Strike\"",
    "2": "Bullet Sign \"Eagle Shooting\"",
    "5": "Bullet Sign \"The Eagle Has Shot Its Target\"",
    "6": "Gun Sign \"Normal Gun\"",
    "9": "Gun Sign \"Normal Gun\"",
    "10": "Rabbit Sign \"Strawberry Dango\"",
    "12": "Rabbit Sign \"Berry Berry Dango\"",
    "14": "Rabbit Sign \"Dango Influence\"",
    "18": "Moon-Viewing \"September Full Moon\"",
    "21": "Moon-Viewing Saké \"Normal September\"",
    "22": "Dream Sign \"Scarlet Nightmare\"",
    "24": "Dream Sign \"Scarlet Oppressive Nightmare\"",
    "26": "Dream Sign \"Indigo Dream of Anxiety\"",
    "28": "Dream Sign \"Indigo Three-Layered Dream of Anxiety\"",
    "29": "Dream Sign \"Eternally Anxious Dream\"",
    "30": "Dream Sign \"Ochre Confusion\"",
    "32": "Dream Sign \"Ochre Labyrinthine Confusion\"",
    "34": "Dream Sign \"Dream Catcher\"",
    "36": "Dream Sign \"Azure Dream Catcher\"",
    "37": "Dream Sign \"Losing Oneself in a Dream\"",
    "38": "Moon Sign \"Ultramarine Normal Dream\"",
    "42": "Orb Sign \"Disorderly Flock's Curse\"",
    "44": "Orb Sign \"Disorderly Flock's Reverse Curse\"",
    "46": "Orb Sign \"Impure Body Detection Mines\"",
    "48": "Orb Sign \"Impure Body Detection Mines V2\"",
    "50": "Orb Sign \"Shotgun Coronation of the Gods\"",
    "52": "Orb Sign \"Shining Shotgun Coronation of the Gods\"",
    "54": "\"One-Winged White Heron\"",
    "58": "Hell Sign \"Hell Eclipse\"",
    "60": "Hell Sign \"Eclipse of Hell\"",
    "62": "Hell Sign \"Flash and Stripe\"",
    "64": "Hell Sign \"Star and Stripe\"",
    "66": "Hellfire \"Graze Inferno\"",
    "69": "Hellfire \"Infernal Essence of Grazing\"",
    "70": "Inferno \"Striped Abyss\"",
    "74": "\"Fake Apollo\"",
    "76": "\"Apollo Hoax Theory\"",
    "78": "\"Pure Light of the Palm\"",
    "82": "\"Murderous Lilies\"",
    "86": "\"Primordial Divine Spirit World\"",
    "88": "\"Modern Divine Spirit World\"",
    "90": "\"Trembling, Shivering Star\"",
    "94": "\"Pristine Lunacy\"",
    "98": "\"Overflowing Blemishes\"",
    "101": "\"Refinement of Earthen Impurity\"",
    "102": "Pure Sign \"Purely Bullet Hell\"",
    "104": "Pure Sign \"A Pristine Danmaku Hell\"",
    "106": "Butterfly \"Butterfly Supplantation\"",
    "107": "Super-Express \"Dream Express\"",
    "108": "Crawling Dream \"Creeping Bullet\"",
    "109": "Otherworld \"Oumagatoki\"",
    "110": "Earth \"Impurity Within One's Body\"",
    "111": "Moon \"Apollo Reflection Mirror\"",
    "112": "\"Simple Danmaku for Cornering a Trapped Rat\"",
    "113": "Otherworld \"Hell's Non-Ideal Danmaku\"",
    "114": "Earth \"Rain Falling in Hell\"",
    "115": "Moon \"Normal Impact\"",
    "116": "\"Pristine Danmaku for Killing a Person\"",
    "117": "\"Trinitarian Rhapsody\"",
    "118": "\"First and Last Nameless Danmaku\"",
    "45": "Orb Sign \"Disorderly Flock's Duplex Curse\""
}
